### PR TITLE
Add multipleOf:$1 validation rule

### PR DESCRIPTION
**Pull request by sendyhalim**
This rule will make sure that the given field is a multiple of `n`

### CODE REVIEW

**Comment by febrianyuwono** [comment]
@sendyhalim please add the indonesian's translation too (src/locale/id.js)

**Comment by sendyhalim** [comment]
@febrianyuwono Oh right!

**Comment by febrianyuwono** [comment]
lgtm

**Comment by sendyhalim** [comment]
Thanks feb!

**Pull request merged**
